export interface countriesData {
  code: string;
  labelEN: string;
  label: string;
}

export const countriesData: countriesData[] = [
  { code: 'GBR', labelEN: 'United Kingdom', label: 'Великобритания' },
  { code: 'ITA', labelEN: 'Italy', label: 'Италия' },
  { code: 'BLZ', labelEN: 'Belize', label: 'Белиз' },
  { code: 'MEX', labelEN: 'Mexico', label: 'Мексика' },
  { code: 'MNE', labelEN: 'Montenegro', label: 'Черногория' },
  { code: 'FRA', labelEN: 'France', label: 'Франция' },
  { code: 'PAN', labelEN: 'Panama', label: 'Панама' },
  { code: 'TUR', labelEN: 'Turkey', label: 'Турция' },
  { code: 'HRV', labelEN: 'Croatia', label: 'Хорватия' },
  { code: 'ZAF', labelEN: 'South Africa', label: 'ЮАР' },
  { code: 'IDN', labelEN: 'Indonesia', label: 'Индонезия' },
  { code: 'CZE', labelEN: 'Czech Republic', label: 'Чехия' },
  { code: 'COL', labelEN: 'Colombia', label: 'Колумбия' },
  { code: 'CHE', labelEN: 'Switzerland', label: 'Швейцария' },
  { code: 'GRC', labelEN: 'Greece', label: 'Греция' },
  { code: 'ESP', labelEN: 'Spain', label: 'Испания' },
  { code: 'PRT', labelEN: 'Portugal', label: 'Португалия' },
  { code: 'NLD', labelEN: 'Netherlands', label: 'Нидерланды' },
  { code: 'LKA', labelEN: 'Sri Lanka', label: 'Шри-Ланка' },
  { code: 'THA', labelEN: 'Thailand', label: 'Таиланд' },
  { code: 'PER', labelEN: 'Peru', label: 'Перу' },
  {
    code: 'TZA',
    labelEN: 'Tanzania, United Republic of',
    label: 'Танзания',
  },
  {
    code: 'CHN',
    labelEN: 'China',
    label: 'КНР (Китайская Народная Республика)',
  },
  { code: 'TUN', labelEN: 'Tunisia', label: 'Тунис' },
  { code: 'ARE', labelEN: 'United Arab Emirates', label: 'ОАЭ' },
  { code: 'AUT', labelEN: 'Austria', label: 'Австрия' },
  { code: 'IRL', labelEN: 'Ireland', label: 'Ирландия' },
  { code: 'AUS', labelEN: 'Australia', label: 'Австралия' },
  { code: 'OMN', labelEN: 'Oman', label: 'Оман' },
  { code: 'ECU', labelEN: 'Ecuador', label: 'Эквадор' },
  { code: 'CHL', labelEN: 'Chile', label: 'Чили' },
  { code: 'CRI', labelEN: 'Costa Rica', label: 'Коста-Рика' },
  { code: 'DEU', labelEN: 'Germany', label: 'Германия' },
  { code: 'BEL', labelEN: 'Belgium', label: 'Бельгия' },
  { code: 'HUN', labelEN: 'Hungary', label: 'Венгрия' },
  { code: 'PRY', labelEN: 'Paraguay', label: 'Парагвай' },
  { code: 'ARG', labelEN: 'Argentina', label: 'Аргентина' },
  { code: 'MAR', labelEN: 'Morocco', label: 'Марокко' },
  { code: 'BGR', labelEN: 'Bulgaria', label: 'Болгария' },
  {
    code: 'DOM',
    labelEN: 'Dominican Republic',
    label: 'Доминиканская Республика',
  },
  { code: 'EGY', labelEN: 'Egypt', label: 'Египет' },
  { code: 'MMR', labelEN: 'Myanmar', label: 'Мьянма' },
  { code: 'VNM', labelEN: 'Vietnam', label: 'Вьетнам' },
  { code: 'MYS', labelEN: 'Malaysia', label: 'Малайзия' },
  { code: 'BOL', labelEN: 'Bolivia', label: 'Боливия' },
  { code: 'GTM', labelEN: 'Guatemala', label: 'Гватемала' },
  { code: 'LUX', labelEN: 'Luxembourg', label: 'Люксембург' },
  { code: 'BRA', labelEN: 'Brazil', label: 'Бразилия' },
  { code: 'USA', labelEN: 'United States of America', label: 'США' },
  { code: 'VEN', labelEN: 'Venezuela', label: 'Венесуэла' },
  { code: 'MOZ', labelEN: 'Mozambique', label: 'Мозамбик' },
  {
    code: 'SXM',
    labelEN: 'Sint Maarten (Dutch part)',
    label: 'Синт-Мартен',
  },
  { code: 'URY', labelEN: 'Uruguay', label: 'Уругвай' },
  { code: 'HTI', labelEN: 'Haiti', label: 'Гаити' },
  { code: 'ROU', labelEN: 'Romania', label: 'Румыния' },
  { code: 'SVK', labelEN: 'Slovakia', label: 'Словакия' },
  { code: 'POL', labelEN: 'Poland', label: 'Польша' },
  {
    code: 'MAF',
    labelEN: 'Saint Martin (French part)',
    label: 'Сен-Мартен',
  },
  { code: 'AND', labelEN: 'Andorra', label: 'Андорра' },
  { code: 'JAM', labelEN: 'Jamaica', label: 'Ямайка' },
  { code: 'AIA', labelEN: 'Anguilla', label: 'Ангилья' },
  { code: 'CYP', labelEN: 'Cyprus', label: 'Кипр' },
  { code: 'GEO', labelEN: 'Georgia', label: 'Грузия' },
];
