export interface countriesData {
  code: string;
  labelEN: string;
  labelRU: string;
}

export const countriesData: countriesData[] = [
  { code: 'GBR', labelEN: 'United Kingdom', labelRU: 'Великобритания' },
  { code: 'ITA', labelEN: 'Italy', labelRU: 'Италия' },
  { code: 'BLZ', labelEN: 'Belize', labelRU: 'Белиз' },
  { code: 'MEX', labelEN: 'Mexico', labelRU: 'Мексика' },
  { code: 'MNE', labelEN: 'Montenegro', labelRU: 'Черногория' },
  { code: 'FRA', labelEN: 'France', labelRU: 'Франция' },
  { code: 'PAN', labelEN: 'Panama', labelRU: 'Панама' },
  { code: 'TUR', labelEN: 'Turkey', labelRU: 'Турция' },
  { code: 'HRV', labelEN: 'Croatia', labelRU: 'Хорватия' },
  { code: 'ZAF', labelEN: 'South Africa', labelRU: 'ЮАР' },
  { code: 'IDN', labelEN: 'Indonesia', labelRU: 'Индонезия' },
  { code: 'CZE', labelEN: 'Czech Republic', labelRU: 'Чехия' },
  { code: 'COL', labelEN: 'Colombia', labelRU: 'Колумбия' },
  { code: 'CHE', labelEN: 'Switzerland', labelRU: 'Швейцария' },
  { code: 'GRC', labelEN: 'Greece', labelRU: 'Греция' },
  { code: 'ESP', labelEN: 'Spain', labelRU: 'Испания' },
  { code: 'PRT', labelEN: 'Portugal', labelRU: 'Португалия' },
  { code: 'NLD', labelEN: 'Netherlands', labelRU: 'Нидерланды' },
  { code: 'LKA', labelEN: 'Sri Lanka', labelRU: 'Шри-Ланка' },
  { code: 'THA', labelEN: 'Thailand', labelRU: 'Таиланд' },
  { code: 'PER', labelEN: 'Peru', labelRU: 'Перу' },
  {
    code: 'TZA',
    labelEN: 'Tanzania, United Republic of',
    labelRU: 'Танзания',
  },
  {
    code: 'CHN',
    labelEN: 'China',
    labelRU: 'КНР (Китайская Народная Республика)',
  },
  { code: 'TUN', labelEN: 'Tunisia', labelRU: 'Тунис' },
  { code: 'ARE', labelEN: 'United Arab Emirates', labelRU: 'ОАЭ' },
  { code: 'AUT', labelEN: 'Austria', labelRU: 'Австрия' },
  { code: 'IRL', labelEN: 'Ireland', labelRU: 'Ирландия' },
  { code: 'AUS', labelEN: 'Australia', labelRU: 'Австралия' },
  { code: 'OMN', labelEN: 'Oman', labelRU: 'Оман' },
  { code: 'ECU', labelEN: 'Ecuador', labelRU: 'Эквадор' },
  { code: 'CHL', labelEN: 'Chile', labelRU: 'Чили' },
  { code: 'CRI', labelEN: 'Costa Rica', labelRU: 'Коста-Рика' },
  { code: 'DEU', labelEN: 'Germany', labelRU: 'Германия' },
  { code: 'BEL', labelEN: 'Belgium', labelRU: 'Бельгия' },
  { code: 'HUN', labelEN: 'Hungary', labelRU: 'Венгрия' },
  { code: 'PRY', labelEN: 'Paraguay', labelRU: 'Парагвай' },
  { code: 'ARG', labelEN: 'Argentina', labelRU: 'Аргентина' },
  { code: 'MAR', labelEN: 'Morocco', labelRU: 'Марокко' },
  { code: 'BGR', labelEN: 'Bulgaria', labelRU: 'Болгария' },
  {
    code: 'DOM',
    labelEN: 'Dominican Republic',
    labelRU: 'Доминиканская Республика',
  },
  { code: 'EGY', labelEN: 'Egypt', labelRU: 'Египет' },
  { code: 'MMR', labelEN: 'Myanmar', labelRU: 'Мьянма' },
  { code: 'VNM', labelEN: 'Vietnam', labelRU: 'Вьетнам' },
  { code: 'MYS', labelEN: 'Malaysia', labelRU: 'Малайзия' },
  { code: 'BOL', labelEN: 'Bolivia', labelRU: 'Боливия' },
  { code: 'GTM', labelEN: 'Guatemala', labelRU: 'Гватемала' },
  { code: 'LUX', labelEN: 'Luxembourg', labelRU: 'Люксембург' },
  { code: 'BRA', labelEN: 'Brazil', labelRU: 'Бразилия' },
  { code: 'USA', labelEN: 'United States of America', labelRU: 'США' },
  { code: 'VEN', labelEN: 'Venezuela', labelRU: 'Венесуэла' },
  { code: 'MOZ', labelEN: 'Mozambique', labelRU: 'Мозамбик' },
  {
    code: 'SXM',
    labelEN: 'Sint Maarten (Dutch part)',
    labelRU: 'Синт-Мартен',
  },
  { code: 'URY', labelEN: 'Uruguay', labelRU: 'Уругвай' },
  { code: 'HTI', labelEN: 'Haiti', labelRU: 'Гаити' },
  { code: 'ROU', labelEN: 'Romania', labelRU: 'Румыния' },
  { code: 'SVK', labelEN: 'Slovakia', labelRU: 'Словакия' },
  { code: 'POL', labelEN: 'Poland', labelRU: 'Польша' },
  {
    code: 'MAF',
    labelEN: 'Saint Martin (French part)',
    labelRU: 'Сен-Мартен',
  },
  { code: 'AND', labelEN: 'Andorra', labelRU: 'Андорра' },
  { code: 'JAM', labelEN: 'Jamaica', labelRU: 'Ямайка' },
  { code: 'AIA', labelEN: 'Anguilla', labelRU: 'Ангилья' },
  { code: 'CYP', labelEN: 'Cyprus', labelRU: 'Кипр' },
  { code: 'GEO', labelEN: 'Georgia', labelRU: 'Грузия' },
];
